apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: rise-by-project-cpu-mem-gpu
  namespace: metering
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: projectid
    type: varchar
  - name: request_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: usage_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: request_memory_gib_seconds
    type: double
  - name: usage_memory_gib_seconds
    type: double
  - name: gpu
    type: varchar
  - name: request_gpu_seconds
    type: double
  inputs:
  - name: ReportingStart
    type: time
  - name: ReportingEnd
    type: time
  - default: rise-pod-cpu-mem-gpu-hourly
    name: PodReportName
    type: Report
  query: |
    SELECT 
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}',
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}',
      projectid, 
      sum(request_cpu_core_seconds),
      sum(usage_cpu_core_seconds),
      sum(request_memory_gib_seconds),
      sum(usage_memory_gib_seconds),
      gpu,
      sum(request_gpu_seconds)
    FROM {| reportTableName .Report.Inputs.PodReportName |}
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' 
    GROUP BY projectid, gpu