apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: rise-project-pod-gpu-request
  namespace: metering
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: varchar
    unit: kubernetes_pod
  - name: node
    type: varchar
    unit: kubernetes_node
  - name: namespace
    type: varchar
    unit: kubernetes_namespace
  - name: projectid
    type: varchar
  - name: gpu
    type: varchar
  - name: pod_request_gpu_seconds
    type: double
  inputs:
  - name: ReportingStart
    type: time
  - name: ReportingEnd
    type: time
  - name: ProjectId
    type: string
    required: true
  - default: rise-pod-gpu-request-hourly
    name: PodGpuRequestReportName
    type: Report
  query: |
    SELECT 
      period_start,
      period_end,
      pod, 
      node, 
      namespace, 
      projectid, 
      gpu,
      pod_request_gpu_seconds
    FROM {| reportTableName .Report.Inputs.PodGpuRequestReportName |}
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_start < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' 
    AND projectid LIKE '{| .Report.Inputs.ProjectId |}'
    ORDER BY period_start
