apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: rise-pod-cpu-mem-gpu
  labels:
    operator-metering: "true"
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: varchar
    unit: kubernetes_pod
  - name: node
    type: varchar
    unit: kubernetes_node
  - name: namespace
    type: varchar
    unit: kubernetes_namespace
  - name: projectid
    type: varchar
  - name: request_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: usage_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: request_memory_gib_seconds
    type: double
  - name: usage_memory_gib_seconds
    type: double
  - name: gpu
    type: varchar
  - name: request_gpu_seconds
    type: double
  inputs:
  - name: ReportingStart
    type: time
  - name: ReportingEnd
    type: time
  - default: rise-pod-cpu-request-hourly
    name: PodCpuRequestReportName
    type: Report    
  - default: rise-pod-cpu-usage-hourly
    name: PodCpuUsageReportName
    type: Report    
  - default: rise-pod-memory-request-hourly
    name: PodMemoryRequestReportName
    type: Report    
  - default: rise-pod-memory-usage-hourly
    name: PodMemoryUsageReportName
    type: Report
  - default: rise-pod-gpu-request-hourly
    name: PodGpuRequestReportName
    type: Report
  query: |
    SELECT
        *
    FROM {| reportTableName .Report.Inputs.PodCpuRequestReportName |}
    LEFT JOIN {| reportTableName .Report.Inputs.PodCpuUsageReportName |}
    USING (period_start,period_end,pod,node,namespace,projectid)
    LEFT JOIN {| reportTableName .Report.Inputs.PodMemoryRequestReportName |}
    USING (period_start,period_end,pod,node,namespace,projectid)
    LEFT JOIN {| reportTableName .Report.Inputs.PodMemoryUsageReportName |}
    USING (period_start,period_end,pod,node,namespace,projectid)
    LEFT JOIN {| reportTableName .Report.Inputs.PodGpuRequestReportName |}
    USING (period_start,period_end,pod,node,namespace,projectid)
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_start < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' 
