apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: rise-pvc-usage
  labels:
    operator-metering: "true"
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: persistentvolumeclaim
    type: varchar
  - name: volumename
    type: varchar
  - name: namespace
    type: varchar
    unit: kubernetes_namespace
  - name: storageclass
    type: varchar
  - name: projectid
    type: varchar
  - name: pvc_usage_gib_seconds
    type: double
  inputs:
  - name: ReportingStart
    type: time
  - name: ReportingEnd
    type: time
  - name: PvcUsageDataSource
    type: ReportDataSource
    default: rise-pvc-usage
  query: |
    SELECT
        timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
        timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
        labels['persistentvolumeclaim'] as persistentvolumeclaim,
        labels['volumename'] as volumename,
        labels['namespace'] as namespace,
        labels['storageclass'] as storageclass,
        labels['label_field_cattle_io_projectId'] as projectid,
        sum(amount * timeprecision / (1024 * 1024 * 1024)) as pvc_usage_gib_seconds
    FROM {| dataSourceTableName .Report.Inputs.PvcUsageDataSource |}
    WHERE timestamp  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND timestamp < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' 
    AND element_at(labels, 'label_field_cattle_io_projectId') IS NOT NULL
    AND element_at(labels, 'namespace') IS NOT NULL
    AND element_at(labels, 'storageclass') IS NOT NULL
    AND element_at(labels, 'volumename') IS NOT NULL
    AND element_at(labels, 'persistentvolumeclaim') IS NOT NULL    
    GROUP BY labels['persistentvolumeclaim'],labels['volumename'],labels['storageclass'],labels['namespace'],labels['label_field_cattle_io_projectId']
