apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: rise-by-project-pvc
  labels:
    operator-metering: "true"
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: storageclass
    type: varchar
  - name: projectid
    type: varchar
  - name: pvc_request_gib_seconds
    type: double
  - name: pvc_usage_gib_seconds
    type: double
  inputs:
  - name: ReportingStart
    type: time
  - name: ReportingEnd
    type: time
  - name: PvcReport
    type: Report
    default: rise-pvc-hourly
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}',
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}',
      storageclass,
      projectid,
      sum(pvc_request_gib_seconds) as pvc_request_gib_seconds,
      sum(pvc_usage_gib_seconds) as pvc_usage_gib_seconds
    FROM {| reportTableName .Report.Inputs.PvcReport |}
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_start < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' 
    GROUP BY (projectid, storageclass)