apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-reports
  namespace: metering
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-dbrt8
roleRef:
  kind: Role
  name: report-reader
  apiGroup: rbac.authorization.k8s.io

