apiVersion: metering.openshift.io/v1
kind: ReportDataSource
metadata:
  name: rise-pvc-usage
spec:
  prometheusMetricsImporter:
    query: |
      max(label_replace(max(kubelet_volume_stats_used_bytes) by (exported_namespace, persistentvolumeclaim), "namespace", "$1", "exported_namespace", "(.+)")) by (namespace, persistentvolumeclaim) + on (namespace, persistentvolumeclaim) group_left(storageclass, volumename) sum(kube_persistentvolumeclaim_info) by (namespace, persistentvolumeclaim, storageclass, volumename) * 0 + on (namespace) group_left (label_field_cattle_io_projectId) max(kube_namespace_labels) by (namespace, label_field_cattle_io_projectId) * 0
