apiVersion: metering.openshift.io/v1
kind: ReportDataSource
metadata:
  name: rise-pod-cpu-usage
spec:
  prometheusMetricsImporter:
    query: |
      sum(rate(container_cpu_usage_seconds_total{image!="",container_name!="POD",container_name!="",pod!=""}[5m])) BY (pod, namespace, node) + on (namespace) group_left (label_field_cattle_io_projectId) max(kube_namespace_labels) by (namespace, label_field_cattle_io_projectId) * 0