apiVersion: metering.openshift.io/v1
kind: ReportDataSource
metadata:
  name: rise-pod-gpu-request
spec:
  prometheusMetricsImporter:
    query: |
      sum(kube_pod_container_resource_requests{resource=~".*gpu", container!="",container!="POD", node!=""}) by (pod, resource, node, namespace) + on (namespace) group_left (label_field_cattle_io_projectId) max(kube_namespace_labels) by (namespace, label_field_cattle_io_projectId) * 0 + on(node) group_left (label_accelerator) max(kube_node_labels) by (node, label_accelerator) * 0
