apiVersion: metering.openshift.io/v1
kind: ReportDataSource
metadata:
  name: rise-pod-memory-usage
spec:
  prometheusMetricsImporter:
    query: |
      sum(container_memory_usage_bytes{container!="POD", container!="",pod!=""}) by (pod, namespace, node) + on (namespace) group_left (label_field_cattle_io_projectId) max(kube_namespace_labels) by (namespace, label_field_cattle_io_projectId) * 0